/*
Copyright The Feather Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hexiaodai/virtnet/pkg/k8s/apis/virtnet/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBarrels implements BarrelInterface
type FakeBarrels struct {
	Fake *FakeVirtnestV1alpha1
}

var barrelsResource = schema.GroupVersionResource{Group: "virtnest", Version: "v1alpha1", Resource: "barrels"}

var barrelsKind = schema.GroupVersionKind{Group: "virtnest", Version: "v1alpha1", Kind: "Barrel"}

// Get takes name of the barrel, and returns the corresponding barrel object, and an error if there is any.
func (c *FakeBarrels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Barrel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(barrelsResource, name), &v1alpha1.Barrel{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Barrel), err
}

// List takes label and field selectors, and returns the list of Barrels that match those selectors.
func (c *FakeBarrels) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BarrelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(barrelsResource, barrelsKind, opts), &v1alpha1.BarrelList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BarrelList{ListMeta: obj.(*v1alpha1.BarrelList).ListMeta}
	for _, item := range obj.(*v1alpha1.BarrelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested barrels.
func (c *FakeBarrels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(barrelsResource, opts))
}

// Create takes the representation of a barrel and creates it.  Returns the server's representation of the barrel, and an error, if there is any.
func (c *FakeBarrels) Create(ctx context.Context, barrel *v1alpha1.Barrel, opts v1.CreateOptions) (result *v1alpha1.Barrel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(barrelsResource, barrel), &v1alpha1.Barrel{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Barrel), err
}

// Update takes the representation of a barrel and updates it. Returns the server's representation of the barrel, and an error, if there is any.
func (c *FakeBarrels) Update(ctx context.Context, barrel *v1alpha1.Barrel, opts v1.UpdateOptions) (result *v1alpha1.Barrel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(barrelsResource, barrel), &v1alpha1.Barrel{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Barrel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBarrels) UpdateStatus(ctx context.Context, barrel *v1alpha1.Barrel, opts v1.UpdateOptions) (*v1alpha1.Barrel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(barrelsResource, "status", barrel), &v1alpha1.Barrel{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Barrel), err
}

// Delete takes name of the barrel and deletes it. Returns an error if one occurs.
func (c *FakeBarrels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(barrelsResource, name, opts), &v1alpha1.Barrel{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBarrels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(barrelsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BarrelList{})
	return err
}

// Patch applies the patch and returns the patched barrel.
func (c *FakeBarrels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Barrel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(barrelsResource, name, pt, data, subresources...), &v1alpha1.Barrel{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Barrel), err
}
