{{- $_ := include "generate-ca-certs" . }}
{{- $cn := printf "virtnet.io" }}
{{- $ip := .Values.tls.extraIpAddresses }}
{{- $dns1 := printf "%s.%s" "virtnet-ctrl" .Release.Namespace }}
{{- $dns2 := printf "%s.%s.svc" "virtnet-ctrl" .Release.Namespace }}
{{- $dns3 := printf "%s.%s.svc.%s" "virtnet-ctrl" .Release.Namespace "cluster.local" }}
{{- $dns := prepend .Values.tls.extraDnsNames $dns1 }}
{{- $dns = prepend $dns $dns2 }}
{{- $dns = prepend $dns $dns3 }}
{{- $dns = prepend $dns $cn }}
{{- $cert := genSignedCert $cn $ip $dns (.Values.tls.caExpiration | int) .ca }}
apiVersion: v1
kind: Secret
metadata:
  name: virtnet-webhook-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key  | b64enc }}
---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: virtnet-webhook
webhooks:
  - name: subnets.virtnet.io
    rules:
      - apiGroups:
          - virtnet.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - subnets
    clientConfig:
      # url: https://192.168.1.16:8081/validate-virtnet-io-v1alpha1-ippool
      service:
        namespace: {{ .Release.Namespace }}
        name: virtnet-ctrl
        path: /validate-virtnet-io-v1alpha1-subnet
        port: 8081
      caBundle: {{ .ca.Cert | b64enc }}
      # caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUYrakNDQStLZ0F3SUJBZ0lKQU0vbDdWd1F1L3VPTUEwR0NTcUdTSWIzRFFFQkRRVUFNRjB4Q3pBSkJnTlYKQkFZVEFrTk9NUkV3RHdZRFZRUUlEQWhUYUdGdVowaGhhVEVSTUE4R0ExVUVCd3dJVTJoaGJtZElZV2t4RVRBUApCZ05WQkFvTUNFUmhiME5zYjNWa01SVXdFd1lEVlFRRERBd3hPVEl1TVRZNExqRXVNVFl3SUJjTk1qUXdNVEl3Ck1EUXdPVEE1V2hnUE1qRXlNekV5TWpjd05EQTVNRGxhTUYweEN6QUpCZ05WQkFZVEFrTk9NUkV3RHdZRFZRUUkKREFoVGFHRnVaMGhoYVRFUk1BOEdBMVVFQnd3SVUyaGhibWRJWVdreEVUQVBCZ05WQkFvTUNFUmhiME5zYjNWawpNUlV3RXdZRFZRUUREQXd4T1RJdU1UWTRMakV1TVRZd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3CmdnSUtBb0lDQVFDNEhjS1FkcHFZSENuVXFnK2JRS08rWTRSaUJ1NmduS21Zcmo3emc4Vm5mbmpIamY3UElPODIKMlJrTE1VbTdvWE1Fd0NNVFVVcjBmOEZTWTU2MHBZSTVEQmpzbXhsaGVnWFhZT1VDODFUVXFQaGV6TElUVmd5Rwo5RzY1NWVIZWNGY1V3ajNpOU84dUZoNTZBYnNkZjMzbXN0aGFjdGZDVytvMjRDUmdabVBpMGtuMEVsZmJRMXRDCmFXS2pFYjY2Y0dpSjVQS0lLOTFDQTl6NzFFTGg4NDlkV0RBZ2tSY2FVMi9aTngydTkwSkhXanRZS2RsQlZBaC8KM1FNSEFYTmM3am9WYzd1dXlrVkF0SGtxZExKWHVLTE9BSXc3UjVXeVFsdXhVYldLOGlLK1IwMnZoSnl6aThiSAo1b2dIVDVZT21PNXlKcW94S3JHaHZKYXpCVktSUzIxbHVDaUJzeWtHeitVZ09tb0hoblpGV0NlOVBqOWpranh0ClEvNGJBWVBObWxZazJwbCs4S1FjT0ZNaFhOOVU5dVdMQVltaGVXa2VTTTNDSmZ5NHNRMFJLUGd1Lys5UERtN1YKc1BNYkx0OVNsdlc2WFQrc0tYUnhDMXltUWp1SHhDWjRxemVHUEJsMGpOTmtqQkVKb0orS2JBYnVaZ2doTHdQbwpDbkUvOGVtQ0huOCs1N1hkcDg4TTJHWFRoNCs0dkJlVEE3M2c4cllSeFNYQTM0UGxwT1hndmw0T3RJRXhXOG9BCjhPK1BheUF2dGdzc3IrOFhiS3pYQ2hpVzVERGpROER3L1oxSkhzbDFkRjc5WjFIWlBTVitLNWdwVXJMMlB4RjgKWGcyNVpEZXc4bHo3TnhpYyticXloWExLQmRXc2lKZjkzYlZtcTNQcTllZ09qTGRTeWlPN0dRSURBUUFCbzRHNgpNSUczTUhjR0ExVWRJd1J3TUc2aFlhUmZNRjB4Q3pBSkJnTlZCQVlUQWtOT01SRXdEd1lEVlFRSURBaFRhR0Z1ClowaGhhVEVSTUE4R0ExVUVCd3dJVTJoaGJtZElZV2t4RVRBUEJnTlZCQW9NQ0VSaGIwTnNiM1ZrTVJVd0V3WUQKVlFRRERBd3hPVEl1TVRZNExqRXVNVGFDQ1FEakxwRzJyMlRmdURBSkJnTlZIUk1FQWpBQU1Bc0dBMVVkRHdRRQpBd0lFOERBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQVBCZ05WSFJFRUNEQUdod1RBcUFFUU1BMEdDU3FHClNJYjNEUUVCRFFVQUE0SUNBUUNmbFNDTWFCb3FKZFV0aEtldS8zb3NaMGp2MVFUU3hRSk9BdGZYRW1aWmFwNUcKYlM0blhYU0EwSVBmOEdjeFZncWdxc0xadjllaFpCZWZ1RndLK3Yzc0RiaGV0S0s1MTZKbkoxUmZvZW9xa2JCbgpCSTBnOFJPYVY5b2xIa2xuUytrOERZTGlkWVFDQnNCWG4zczh3Zy9zOWpPTHZsVVF6R3d6VWlMNy9rTjRDdzB1Cmpjd1dETTZPbkNiNkFoVjAvbklBbjVibTBKRm9NczBBNWFjQStreVp3ODV3TFRqa3dxWngzbmhQd3VpVW51UVAKZC8xSmg4c1JTK0dUbVc0cEw2VzBkZEdvbDdHc3o3QzUzb2dkNXVKYVJYTnJQck0zRE8vMHprYXpYd0JNczBVQgpndDhCZ2NZME90Yy9zT2VhSmk2UWcyYkIzZmsrUHRhc0kzVmxEY0VibzI3bWtjSjZCRUpONjV6T0Y4QUp6VEhHCnZPZUZMQTh5ajhpREg2ZVZkZHJkZmhxUTNjaFhybnBxbjNPQzVKR3BJZUtIM3JuakRNbUJ4MkZWY0xYNGZsckYKU1FuOXRXcnFONDQyVUdrUG9GYVVFVzZGR1Jsd2s0TlljYW1SYzZDNkdHZE1HRkJIWFk0ajBML1g5REpTam04dwo3U09QTE1BNUpEMjJWZmliVUpmYXEvVVNJaFNOUUY2M1BWQzJMODIzMWpPcDdLYWkwL3A1QXNtME5WKzlmendsCk1ETlVhOUNicUtjbFRhTldia0hwZW1nZTRIWVRnVUdqemVyd2dsamxZUi94dDVHRENVbkcxQWJtMGRUNisxblMKbFJVWkVlaTBNaCsyRTRaVHlQd2s0TU5hU2xoWlRBNVo3UEUxZVp6RDJ2VjExSy9vTTF3TWlVd3FDS3VLSkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    sideEffects: None
---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: virtnet-webhook
webhooks:
  - name: subnets.virtnet.io
    rules:
      - apiGroups:
          - virtnet.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - subnets
    clientConfig:
      # url: https://192.168.1.16:8081/mutate-virtnet-io-v1alpha1-ippool
      service:
        namespace: {{ .Release.Namespace }}
        name: virtnet-ctrl
        path: /mutate-virtnet-io-v1alpha1-subnet
        port: 8081
      caBundle: {{ .ca.Cert | b64enc }}
      # caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUYrakNDQStLZ0F3SUJBZ0lKQU0vbDdWd1F1L3VPTUEwR0NTcUdTSWIzRFFFQkRRVUFNRjB4Q3pBSkJnTlYKQkFZVEFrTk9NUkV3RHdZRFZRUUlEQWhUYUdGdVowaGhhVEVSTUE4R0ExVUVCd3dJVTJoaGJtZElZV2t4RVRBUApCZ05WQkFvTUNFUmhiME5zYjNWa01SVXdFd1lEVlFRRERBd3hPVEl1TVRZNExqRXVNVFl3SUJjTk1qUXdNVEl3Ck1EUXdPVEE1V2hnUE1qRXlNekV5TWpjd05EQTVNRGxhTUYweEN6QUpCZ05WQkFZVEFrTk9NUkV3RHdZRFZRUUkKREFoVGFHRnVaMGhoYVRFUk1BOEdBMVVFQnd3SVUyaGhibWRJWVdreEVUQVBCZ05WQkFvTUNFUmhiME5zYjNWawpNUlV3RXdZRFZRUUREQXd4T1RJdU1UWTRMakV1TVRZd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3CmdnSUtBb0lDQVFDNEhjS1FkcHFZSENuVXFnK2JRS08rWTRSaUJ1NmduS21Zcmo3emc4Vm5mbmpIamY3UElPODIKMlJrTE1VbTdvWE1Fd0NNVFVVcjBmOEZTWTU2MHBZSTVEQmpzbXhsaGVnWFhZT1VDODFUVXFQaGV6TElUVmd5Rwo5RzY1NWVIZWNGY1V3ajNpOU84dUZoNTZBYnNkZjMzbXN0aGFjdGZDVytvMjRDUmdabVBpMGtuMEVsZmJRMXRDCmFXS2pFYjY2Y0dpSjVQS0lLOTFDQTl6NzFFTGg4NDlkV0RBZ2tSY2FVMi9aTngydTkwSkhXanRZS2RsQlZBaC8KM1FNSEFYTmM3am9WYzd1dXlrVkF0SGtxZExKWHVLTE9BSXc3UjVXeVFsdXhVYldLOGlLK1IwMnZoSnl6aThiSAo1b2dIVDVZT21PNXlKcW94S3JHaHZKYXpCVktSUzIxbHVDaUJzeWtHeitVZ09tb0hoblpGV0NlOVBqOWpranh0ClEvNGJBWVBObWxZazJwbCs4S1FjT0ZNaFhOOVU5dVdMQVltaGVXa2VTTTNDSmZ5NHNRMFJLUGd1Lys5UERtN1YKc1BNYkx0OVNsdlc2WFQrc0tYUnhDMXltUWp1SHhDWjRxemVHUEJsMGpOTmtqQkVKb0orS2JBYnVaZ2doTHdQbwpDbkUvOGVtQ0huOCs1N1hkcDg4TTJHWFRoNCs0dkJlVEE3M2c4cllSeFNYQTM0UGxwT1hndmw0T3RJRXhXOG9BCjhPK1BheUF2dGdzc3IrOFhiS3pYQ2hpVzVERGpROER3L1oxSkhzbDFkRjc5WjFIWlBTVitLNWdwVXJMMlB4RjgKWGcyNVpEZXc4bHo3TnhpYyticXloWExLQmRXc2lKZjkzYlZtcTNQcTllZ09qTGRTeWlPN0dRSURBUUFCbzRHNgpNSUczTUhjR0ExVWRJd1J3TUc2aFlhUmZNRjB4Q3pBSkJnTlZCQVlUQWtOT01SRXdEd1lEVlFRSURBaFRhR0Z1ClowaGhhVEVSTUE4R0ExVUVCd3dJVTJoaGJtZElZV2t4RVRBUEJnTlZCQW9NQ0VSaGIwTnNiM1ZrTVJVd0V3WUQKVlFRRERBd3hPVEl1TVRZNExqRXVNVGFDQ1FEakxwRzJyMlRmdURBSkJnTlZIUk1FQWpBQU1Bc0dBMVVkRHdRRQpBd0lFOERBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQVBCZ05WSFJFRUNEQUdod1RBcUFFUU1BMEdDU3FHClNJYjNEUUVCRFFVQUE0SUNBUUNmbFNDTWFCb3FKZFV0aEtldS8zb3NaMGp2MVFUU3hRSk9BdGZYRW1aWmFwNUcKYlM0blhYU0EwSVBmOEdjeFZncWdxc0xadjllaFpCZWZ1RndLK3Yzc0RiaGV0S0s1MTZKbkoxUmZvZW9xa2JCbgpCSTBnOFJPYVY5b2xIa2xuUytrOERZTGlkWVFDQnNCWG4zczh3Zy9zOWpPTHZsVVF6R3d6VWlMNy9rTjRDdzB1Cmpjd1dETTZPbkNiNkFoVjAvbklBbjVibTBKRm9NczBBNWFjQStreVp3ODV3TFRqa3dxWngzbmhQd3VpVW51UVAKZC8xSmg4c1JTK0dUbVc0cEw2VzBkZEdvbDdHc3o3QzUzb2dkNXVKYVJYTnJQck0zRE8vMHprYXpYd0JNczBVQgpndDhCZ2NZME90Yy9zT2VhSmk2UWcyYkIzZmsrUHRhc0kzVmxEY0VibzI3bWtjSjZCRUpONjV6T0Y4QUp6VEhHCnZPZUZMQTh5ajhpREg2ZVZkZHJkZmhxUTNjaFhybnBxbjNPQzVKR3BJZUtIM3JuakRNbUJ4MkZWY0xYNGZsckYKU1FuOXRXcnFONDQyVUdrUG9GYVVFVzZGR1Jsd2s0TlljYW1SYzZDNkdHZE1HRkJIWFk0ajBML1g5REpTam04dwo3U09QTE1BNUpEMjJWZmliVUpmYXEvVVNJaFNOUUY2M1BWQzJMODIzMWpPcDdLYWkwL3A1QXNtME5WKzlmendsCk1ETlVhOUNicUtjbFRhTldia0hwZW1nZTRIWVRnVUdqemVyd2dsamxZUi94dDVHRENVbkcxQWJtMGRUNisxblMKbFJVWkVlaTBNaCsyRTRaVHlQd2s0TU5hU2xoWlRBNVo3UEUxZVp6RDJ2VjExSy9vTTF3TWlVd3FDS3VLSkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    sideEffects: None
