apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtnet-ctrl
  namespace: {{ .Release.Namespace }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtnet-ctrl
  namespace: {{ .Release.Namespace }}
  labels:
    app: virtnet-ctrl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtnet-ctrl
  template:
    metadata:
      labels:
        app: virtnet-ctrl
    spec:
      hostNetwork: true
      containers:
      - name: virtnet-ctrl
        env:
        - name: LOG_LEVEL
          value: debug
        image: {{ .Values.deployment.ctrl.image.repository }}:{{ .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        resources:
        {{- toYaml .Values.deployment.ctrl.resources | nindent 10 }}
        volumeMounts:
        - name: virtnet-webhook-secret
          mountPath: /etc/virtnet/secret
          readOnly: true
      serviceAccountName: virtnet-ctrl
      volumes:
      - name: virtnet-webhook-secret
        secret:
          secretName: virtnet-webhook-secret
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: virtnet-ctrl
    service: virtnet-ctrl
  name: virtnet-ctrl
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: virtnet-ctrl
  type: ClusterIP
  ports:
  - name: webhook-port
    port: 8081
    protocol: TCP
    targetPort: 8081
