apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtnet
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - "*"
  - nonResourceURLs:
      - '*'
    verbs:
      - "*"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtnet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtnet
subjects:
  - kind: ServiceAccount
    name: virtnet-agent
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: virtnet-ctrl
    namespace: {{ .Release.Namespace }}
