apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan
  namespace: kube-system
spec:
  config: '{"cniVersion":"0.3.1","name":"macvlan","plugins":[{"type":"macvlan","master":"eth0","mode":"bridge","ipam":{"type":"virtnest-ipam","default_ipv4_ippool":["macvlan-default-ipv4"]}}]}'
