---
# Source: chart-virtnet/templates/virtnet-agent.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtnet-agent
  namespace: virtnet
---
# Source: chart-virtnet/templates/virtnet-ctrl.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtnet-ctrl
  namespace: virtnet
---
# Source: chart-virtnet/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: virtnet-webhook-secret
  namespace: virtnet
type: kubernetes.io/tls
data:
  ca.crt:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGekNDQWYrZ0F3SUJBZ0lRZUZJMnpEZTRRMGdEV1hGaEp0a0hkakFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwMmFYSjBibVYwTG1sdk1DQVhEVEkwTURJd05UQTNOVEV4TUZvWUR6SXlNak14TWpFNQpNRGMxTVRFd1dqQVZNUk13RVFZRFZRUURFd3AyYVhKMGJtVjBMbWx2TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBeTF5SWRJK0lKR2FnYUR3MFRmNlVVUmNJSVN4UkJyeWREaC94SkdpR3NhdHcKaVdacjBVVi8wdkx6VWpkUlk5Tm5YS3VENGFycWl4MlA2TWQrbzBWYkJkV25CZ0RzSEx4TlpETlhWQ0E2cUZoQgpFRGY5MzBrbWg5UG9CTTFPS0pvZkxsL095cDVWWWY1U0Z4Y3FpUVIxSENXZSs4VC9tZ1U0bVhaYlQ1VTFNb1dTCnVYR3FERFY0M3NPMWNweXh4REZJU0ZGbVp0eVNLelRFM1dvRWw2UWhHWXFSaXhzT0JXWlF2andlL0V0QmFTSFAKOHlxaUd2Nmk5aDZnSzRtUVA0TkltRkpmTlc3aU83V2MyT09lMmhTZXd5YXYvNWlXWUhwT1RWbEozMWk1bVpXMwpvMjZ0TmNsZHU4cXRCUllJUG1zSHFnZnREYm84d3pJejc1bGFUU2Z4ZFFJREFRQUJvMkV3WHpBT0JnTlZIUThCCkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIKL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkJwc3E2TFNoaHpIWm1ydmtNUVd5RmxON1Vha01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNERTd1VUJQYkFlaVJlc0V0VFIyNXVKa3FHdW4vSTJkN28rT0VVa0tuYTh0Uk9VQnEyCkFhWVVxWlNNQVJBNm9YaHBaVUFvb3Y2VmRaOEIxS3hUak5YdzU4T01LK2kwWmxoS2lqVTNsOWIrTkVtQ1I1NFEKeVJ0NXljVFJZb1ljYzNBUDJEcGNSMXBxcXdoUG1lM0lnOUszYVgvVWFneFFWZmFQanBBSUFkd2hCSHZVY2VUdwpXaVowNG9tM0pBNmtLQXIrZVBjRU5kcWJLSVRrZVZVTE9jVVNhc3YwSnAyZXNsNjhRb2d0dEVRcEhhRHdVR2tWCjByc2R2ZDM4MzZoZ2tRbE53Y2l1cW9EN0Y2VFVORitPdEdObDExNDY1d1dueEI0eTI4YWZpOGYxT3U4YWJDdUgKSFVtLzJuZ3VWdEk2UEhLOXZoM0E4eFZCbng4S1Q4b0psNzgrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiVENDQWxXZ0F3SUJBZ0lSQUs2cUoybWdMeWRLcHVKckxwQXZuYUl3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2RtbHlkRzVsZEM1cGJ6QWdGdzB5TkRBeU1EVXdOelV4TVRGYUdBOHlNakl6TVRJeApPVEEzTlRFeE1Wb3dGVEVUTUJFR0ExVUVBeE1LZG1seWRHNWxkQzVwYnpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUxCbVc3T04vTkZhLzZOTUJuYlZITDhoQXgvN3FIaHhZOE1JdVA5QkZyOHMKWTFCNGJUbytBMHNWYnI0SWtyb3p1T0E2QlJ4cllDcDdvMC9BbnQrR1g5OHR0ODFZTy9nYUdHN0J1eUMrTERpOApnOUdyclUzTTZiNGhYNi9zdVQ0Vm11R3RUc08wZGlXNXlSWStJSGU3ckE2UVh1MUZVMVRRZlJYRE5yZHA5Yk15Cno0Q2c5cndqRHo2WThNTDVvaDEvN09Wa1dzRTZwbWYwRkVxQXNaYjVyMUo3a3pqc1g5NjZDaVc1TmIyNmI4UGMKaU1oQU1zUlE5aENTTzZTYWFSUWhDcFIxdHhnRERtcVhRMkk0YWR3TTBPV1ltOWcyRE1hbXJ5c2I4ZWsyczVuMwpia2hGZElsQnV2NklQd2FKREE1TGxZRXpVREU3L280ZjJ5S3l4Um1TVEhVQ0F3RUFBYU9CdFRDQnNqQU9CZ05WCkhROEJBZjhFQkFNQ0JhQXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUF3R0ExVWQKRXdFQi93UUNNQUF3Y3dZRFZSMFJCR3d3YW9JS2RtbHlkRzVsZEM1cGI0SW1kbWx5ZEc1bGRDMWpkSEpzTG5acApjblJ1WlhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd5Q0dIWnBjblJ1WlhRdFkzUnliQzUyYVhKMGJtVjBMbk4yClk0SVVkbWx5ZEc1bGRDMWpkSEpzTG5acGNuUnVaWFNIQkg4QUFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUIKQUQ3Z2xJUWRGaU0raGowN0pmZlBZaURQWGcxU1U1Q0hMK0RJbjZ4aG1yN3RwaDhIWjhLbmkwUFVQaEUyRjhsTApaMktBTWZhTTBuYXIyR1FwVW5FVGk5aFNVNjc5SldqNnRHZTE4Y3ZMUGRyeE1Ga3dmUWwrY3ZxZFZNdk94Wko4CnFicnhrdXZGUTlkdno4NmhVRmdCQkVobUR2RGl2MGw2QjY1dkMxK1lha0lucmFON0lHbnE4a2JmejJuMzlXbmUKZ1JRQW5vNUNFUk9ldkFpRllBM2RQbGNyN0VHb0UzckN2S1VRbGIvV1lWNGlrVjdzMXNtdUxmMG5PVUR6Ylp3awp3a1R3T0dwQ0JPVmNkZE8yaGZyQ2lxQzQxYm1iYXJUb09BTVRKaHFveTYzSHp3cFozNGFxSDRjanhJNC9UeVhxCjdJcGZ6dkJtTVVZZ2YrVUxJdFVLSmlZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBc0daYnM0MzgwVnIvbzB3R2R0VWN2eUVESC91b2VIRmp3d2k0LzBFV3Z5eGpVSGh0Ck9qNERTeFZ1dmdpU3VqTzQ0RG9GSEd0Z0tudWpUOENlMzRaZjN5MjN6Vmc3K0JvWWJzRzdJTDRzT0x5RDBhdXQKVGN6cHZpRmZyK3k1UGhXYTRhMU93N1IySmJuSkZqNGdkN3VzRHBCZTdVVlRWTkI5RmNNMnQybjFzekxQZ0tEMgp2Q01QUHBqd3d2bWlIWC9zNVdSYXdUcW1aL1FVU29DeGx2bXZVbnVUT094ZjNyb0tKYmsxdmJwdnc5eUl5RUF5CnhGRDJFSkk3cEpwcEZDRUtsSFczR0FNT2FwZERZamhwM0F6UTVaaWIyRFlNeHFhdkt4dng2VGF6bWZkdVNFVjAKaVVHNi9vZy9Cb2tNRGt1VmdUTlFNVHYramgvYklyTEZHWkpNZFFJREFRQUJBb0lCQURaaGwrdW0za1g4YzhyMwo2UlpCWlBkWFNndFdIZjNqbHduTmFwcm1pZ2l0dW9CWVgvUVFvaHRIcERoWmxFSnJKNWVZeTNLVGQ3WWhINXU2Cm1qLzJ3UitnaklWMXFpYzJoRW5BMTl1a1JTWEltQ3JQYmtJSjVoV0RYR2h6NWpmSm1WSHhoOUsxazZiVnU3UnIKdXI2dTBNQThxY2NrRkNpVmpicGowRDZESUFmNklybS95NkxScmVJUkFKeHlqOHVvaGtpTzVUaElyUk1RQlJXWApnQS9IMElpc0hVeXJVOW5iVDR3czE4c2FvTjlxZ1pJVU0wWmFtNE02SEgydGxCNGM0SEJMNkt2WlVRNzBRVktVCjF1aTRBSVZBOTBkRXpqd0tVUkh4S0VCUUczbWZ2MHA5ajF6L0xqRFhlcjBuSmo2dHU1OTM2TStiOVdGVXo2dWwKMTJsd1dnRUNnWUVBeGRKRGhDTGl5akF6VVJmRjFWS3RhbHVzUnNoRGxHNFVkVjlyWVFGWFZBbW1YbTBscTNGcQprSFZ0SEwrTkRCQTczbkl6ckE2TkVHWXlLL0JWdndRL2pjTUJnUmRoamFNRlBYd3pvMGp3SGZHVnNIVGdoalNHCnRzWWRZbEZQdnBCTmttbnhCSUdPVDVuTUs2TVNMMjBqa3ZjeDE4R3U3clRBbG9CemE3aWRBNVVDZ1lFQTVFZEwKWXc1MjJMTDZtUS9FbVNzM3BnMlUxSzRJRlI4cGtNSGUzRG15WGxHK3JaQlJLZ3djYTNRSHVnTjM1TkR1SmJEegpyS09seEl2WDdpZVl1WVkyalZOemx5bzNhWFpDRjZiK0JCV0lpVzJIemJ4SUlGVVlkSU9VSmtGaHR0UG1Ed2V0CktQMmlKWnBKRk15MWc0RnQwbXo0WlFlK0QxTndsc2tBTmNIMzdXRUNnWUJLMzRPSWJyL1I4UjVyTWdsQjdaSVAKY0hVck1UOUszY05HallBUjdqVUViTWFZZE0xT0w1WTY2UWNNVzMvaU1mN0crZ2lPdGM4MGhzbTBrYm1TbStRRwpIdW5oMTF5b0JDekdrY3psbjRTcWdMYThXL0JqTzF4RnI0U05vdU1BNkpORHVHOXQyaTluOTNrc2h3TXFDaS90CnZ6d1JRcENZYnJkNS8xSXdVbWF6WlFLQmdGTndwK0tlUDl5M2x4ZnBocEFDRndZd1FxMTJxMmVsQzFscE05L0YKaXlna3N4RFlCb0xiQ0d4U2JoeVU5ZmNDVTNvZGN3UXdrUUFGcWJqWWFsK3Q2alRBUXlrRytsZ25MTU5lZTh6YwpYaHIxbVVVZlJESGxTTm9WMmtvZGJlMFpDU2VIUThrTzVIemdKMFJlQ3g3MWFVSVlLTGN0SEZDWHpEaWhZZDFFCmVDNGhBb0dCQUlHWCtXdGxLZ3RlWDY1VDNvVWpvbDZpVW9vdm9KdVRjNWFOYkxKcnFQRWlOSXhlWnhMQzZRTUYKTnA3UDNOdGgvSE9ld2sxZXRSQVpvZlBaajd0c0V6S3lMMWY3T3VmNTZwUHdXUW10TU5wSndPYzNKdzhpSlBEcwpKYmlud3E5cXZoSnc3QkUvUWZoSkgzU3A5ZUVWeVhqNnRRUUlDM3hscVlXMkorQmVnSitCCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: chart-virtnet/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: virtnet-conf
  namespace: virtnet
data:
  conf.yml: |
    ipamUnixSocketPath: /var/run/virtnet/virtnet.sock
---
# Source: chart-virtnet/templates/virtnet-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtnet
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - "*"
  - nonResourceURLs:
      - '*'
    verbs:
      - "*"
---
# Source: chart-virtnet/templates/virtnet-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtnet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtnet
subjects:
  - kind: ServiceAccount
    name: virtnet-agent
    namespace: virtnet
  - kind: ServiceAccount
    name: virtnet-ctrl
    namespace: virtnet
---
# Source: chart-virtnet/templates/virtnet-ctrl.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: virtnet-ctrl
    service: virtnet-ctrl
  name: virtnet-ctrl
  namespace: virtnet
spec:
  selector:
    app: virtnet-ctrl
  type: ClusterIP
  ports:
  - name: webhook-port
    port: 8081
    protocol: TCP
    targetPort: 8081
---
# Source: chart-virtnet/templates/virtnet-agent.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: virtnet-agent
  namespace: virtnet
  labels:
    app: virtnet-agent
spec:
  selector:
    matchLabels:
      app: virtnet-agent
  template:
    metadata:
      labels:
        app: virtnet-agent
    spec:
      hostNetwork: true
      initContainers:
      - name: install-plugins
        image: docker.io/hejianmin/virtnet-plugins:v0.2.9-dev
        command:
          - /bin/sh
          - entrypoint.sh
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: cni-bin-path
          mountPath: /host/opt/cni/bin
      containers:
      - name: virtnet-agent
        env:
        - name: LOG_LEVEL
          value: debug
        image: docker.io/hejianmin/virtnet-agent:v0.2.9-dev
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: ipam-unix-socket-dir
          mountPath: /var/run/virtnet
      serviceAccountName: virtnet-agent
      volumes:
      - name: cni-bin-path
        hostPath:
          path: /opt/cni/bin
          type: DirectoryOrCreate
      - name: ipam-unix-socket-dir
        hostPath:
          path: /var/run/virtnet
          type: DirectoryOrCreate
---
# Source: chart-virtnet/templates/virtnet-ctrl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtnet-ctrl
  namespace: virtnet
  labels:
    app: virtnet-ctrl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtnet-ctrl
  template:
    metadata:
      labels:
        app: virtnet-ctrl
    spec:
      hostNetwork: true
      containers:
      - name: virtnet-ctrl
        env:
        - name: LOG_LEVEL
          value: debug
        image: docker.io/hejianmin/virtnet-ctrl:v0.2.9-dev
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: virtnet-webhook-secret
          mountPath: /etc/virtnet/secret
          readOnly: true
      serviceAccountName: virtnet-ctrl
      volumes:
      - name: virtnet-webhook-secret
        secret:
          secretName: virtnet-webhook-secret
---
# Source: chart-virtnet/templates/secret.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: virtnet-webhook
webhooks:
  - name: subnets.virtnet.io
    rules:
      - apiGroups:
          - virtnet.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - subnets
    clientConfig:
      # url: https://192.168.1.16:8081/mutate-virtnet-io-v1alpha1-ippool
      service:
        namespace: virtnet
        name: virtnet-ctrl
        path: /mutate-virtnet-io-v1alpha1-subnet
        port: 8081
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGekNDQWYrZ0F3SUJBZ0lRZUZJMnpEZTRRMGdEV1hGaEp0a0hkakFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwMmFYSjBibVYwTG1sdk1DQVhEVEkwTURJd05UQTNOVEV4TUZvWUR6SXlNak14TWpFNQpNRGMxTVRFd1dqQVZNUk13RVFZRFZRUURFd3AyYVhKMGJtVjBMbWx2TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBeTF5SWRJK0lKR2FnYUR3MFRmNlVVUmNJSVN4UkJyeWREaC94SkdpR3NhdHcKaVdacjBVVi8wdkx6VWpkUlk5Tm5YS3VENGFycWl4MlA2TWQrbzBWYkJkV25CZ0RzSEx4TlpETlhWQ0E2cUZoQgpFRGY5MzBrbWg5UG9CTTFPS0pvZkxsL095cDVWWWY1U0Z4Y3FpUVIxSENXZSs4VC9tZ1U0bVhaYlQ1VTFNb1dTCnVYR3FERFY0M3NPMWNweXh4REZJU0ZGbVp0eVNLelRFM1dvRWw2UWhHWXFSaXhzT0JXWlF2andlL0V0QmFTSFAKOHlxaUd2Nmk5aDZnSzRtUVA0TkltRkpmTlc3aU83V2MyT09lMmhTZXd5YXYvNWlXWUhwT1RWbEozMWk1bVpXMwpvMjZ0TmNsZHU4cXRCUllJUG1zSHFnZnREYm84d3pJejc1bGFUU2Z4ZFFJREFRQUJvMkV3WHpBT0JnTlZIUThCCkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIKL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkJwc3E2TFNoaHpIWm1ydmtNUVd5RmxON1Vha01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNERTd1VUJQYkFlaVJlc0V0VFIyNXVKa3FHdW4vSTJkN28rT0VVa0tuYTh0Uk9VQnEyCkFhWVVxWlNNQVJBNm9YaHBaVUFvb3Y2VmRaOEIxS3hUak5YdzU4T01LK2kwWmxoS2lqVTNsOWIrTkVtQ1I1NFEKeVJ0NXljVFJZb1ljYzNBUDJEcGNSMXBxcXdoUG1lM0lnOUszYVgvVWFneFFWZmFQanBBSUFkd2hCSHZVY2VUdwpXaVowNG9tM0pBNmtLQXIrZVBjRU5kcWJLSVRrZVZVTE9jVVNhc3YwSnAyZXNsNjhRb2d0dEVRcEhhRHdVR2tWCjByc2R2ZDM4MzZoZ2tRbE53Y2l1cW9EN0Y2VFVORitPdEdObDExNDY1d1dueEI0eTI4YWZpOGYxT3U4YWJDdUgKSFVtLzJuZ3VWdEk2UEhLOXZoM0E4eFZCbng4S1Q4b0psNzgrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      # caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUYrakNDQStLZ0F3SUJBZ0lKQU0vbDdWd1F1L3VPTUEwR0NTcUdTSWIzRFFFQkRRVUFNRjB4Q3pBSkJnTlYKQkFZVEFrTk9NUkV3RHdZRFZRUUlEQWhUYUdGdVowaGhhVEVSTUE4R0ExVUVCd3dJVTJoaGJtZElZV2t4RVRBUApCZ05WQkFvTUNFUmhiME5zYjNWa01SVXdFd1lEVlFRRERBd3hPVEl1TVRZNExqRXVNVFl3SUJjTk1qUXdNVEl3Ck1EUXdPVEE1V2hnUE1qRXlNekV5TWpjd05EQTVNRGxhTUYweEN6QUpCZ05WQkFZVEFrTk9NUkV3RHdZRFZRUUkKREFoVGFHRnVaMGhoYVRFUk1BOEdBMVVFQnd3SVUyaGhibWRJWVdreEVUQVBCZ05WQkFvTUNFUmhiME5zYjNWawpNUlV3RXdZRFZRUUREQXd4T1RJdU1UWTRMakV1TVRZd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3CmdnSUtBb0lDQVFDNEhjS1FkcHFZSENuVXFnK2JRS08rWTRSaUJ1NmduS21Zcmo3emc4Vm5mbmpIamY3UElPODIKMlJrTE1VbTdvWE1Fd0NNVFVVcjBmOEZTWTU2MHBZSTVEQmpzbXhsaGVnWFhZT1VDODFUVXFQaGV6TElUVmd5Rwo5RzY1NWVIZWNGY1V3ajNpOU84dUZoNTZBYnNkZjMzbXN0aGFjdGZDVytvMjRDUmdabVBpMGtuMEVsZmJRMXRDCmFXS2pFYjY2Y0dpSjVQS0lLOTFDQTl6NzFFTGg4NDlkV0RBZ2tSY2FVMi9aTngydTkwSkhXanRZS2RsQlZBaC8KM1FNSEFYTmM3am9WYzd1dXlrVkF0SGtxZExKWHVLTE9BSXc3UjVXeVFsdXhVYldLOGlLK1IwMnZoSnl6aThiSAo1b2dIVDVZT21PNXlKcW94S3JHaHZKYXpCVktSUzIxbHVDaUJzeWtHeitVZ09tb0hoblpGV0NlOVBqOWpranh0ClEvNGJBWVBObWxZazJwbCs4S1FjT0ZNaFhOOVU5dVdMQVltaGVXa2VTTTNDSmZ5NHNRMFJLUGd1Lys5UERtN1YKc1BNYkx0OVNsdlc2WFQrc0tYUnhDMXltUWp1SHhDWjRxemVHUEJsMGpOTmtqQkVKb0orS2JBYnVaZ2doTHdQbwpDbkUvOGVtQ0huOCs1N1hkcDg4TTJHWFRoNCs0dkJlVEE3M2c4cllSeFNYQTM0UGxwT1hndmw0T3RJRXhXOG9BCjhPK1BheUF2dGdzc3IrOFhiS3pYQ2hpVzVERGpROER3L1oxSkhzbDFkRjc5WjFIWlBTVitLNWdwVXJMMlB4RjgKWGcyNVpEZXc4bHo3TnhpYyticXloWExLQmRXc2lKZjkzYlZtcTNQcTllZ09qTGRTeWlPN0dRSURBUUFCbzRHNgpNSUczTUhjR0ExVWRJd1J3TUc2aFlhUmZNRjB4Q3pBSkJnTlZCQVlUQWtOT01SRXdEd1lEVlFRSURBaFRhR0Z1ClowaGhhVEVSTUE4R0ExVUVCd3dJVTJoaGJtZElZV2t4RVRBUEJnTlZCQW9NQ0VSaGIwTnNiM1ZrTVJVd0V3WUQKVlFRRERBd3hPVEl1TVRZNExqRXVNVGFDQ1FEakxwRzJyMlRmdURBSkJnTlZIUk1FQWpBQU1Bc0dBMVVkRHdRRQpBd0lFOERBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQVBCZ05WSFJFRUNEQUdod1RBcUFFUU1BMEdDU3FHClNJYjNEUUVCRFFVQUE0SUNBUUNmbFNDTWFCb3FKZFV0aEtldS8zb3NaMGp2MVFUU3hRSk9BdGZYRW1aWmFwNUcKYlM0blhYU0EwSVBmOEdjeFZncWdxc0xadjllaFpCZWZ1RndLK3Yzc0RiaGV0S0s1MTZKbkoxUmZvZW9xa2JCbgpCSTBnOFJPYVY5b2xIa2xuUytrOERZTGlkWVFDQnNCWG4zczh3Zy9zOWpPTHZsVVF6R3d6VWlMNy9rTjRDdzB1Cmpjd1dETTZPbkNiNkFoVjAvbklBbjVibTBKRm9NczBBNWFjQStreVp3ODV3TFRqa3dxWngzbmhQd3VpVW51UVAKZC8xSmg4c1JTK0dUbVc0cEw2VzBkZEdvbDdHc3o3QzUzb2dkNXVKYVJYTnJQck0zRE8vMHprYXpYd0JNczBVQgpndDhCZ2NZME90Yy9zT2VhSmk2UWcyYkIzZmsrUHRhc0kzVmxEY0VibzI3bWtjSjZCRUpONjV6T0Y4QUp6VEhHCnZPZUZMQTh5ajhpREg2ZVZkZHJkZmhxUTNjaFhybnBxbjNPQzVKR3BJZUtIM3JuakRNbUJ4MkZWY0xYNGZsckYKU1FuOXRXcnFONDQyVUdrUG9GYVVFVzZGR1Jsd2s0TlljYW1SYzZDNkdHZE1HRkJIWFk0ajBML1g5REpTam04dwo3U09QTE1BNUpEMjJWZmliVUpmYXEvVVNJaFNOUUY2M1BWQzJMODIzMWpPcDdLYWkwL3A1QXNtME5WKzlmendsCk1ETlVhOUNicUtjbFRhTldia0hwZW1nZTRIWVRnVUdqemVyd2dsamxZUi94dDVHRENVbkcxQWJtMGRUNisxblMKbFJVWkVlaTBNaCsyRTRaVHlQd2s0TU5hU2xoWlRBNVo3UEUxZVp6RDJ2VjExSy9vTTF3TWlVd3FDS3VLSkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    sideEffects: None
---
# Source: chart-virtnet/templates/secret.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: virtnet-webhook
webhooks:
  - name: subnets.virtnet.io
    rules:
      - apiGroups:
          - virtnet.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - subnets
    clientConfig:
      # url: https://192.168.1.16:8081/validate-virtnet-io-v1alpha1-ippool
      service:
        namespace: virtnet
        name: virtnet-ctrl
        path: /validate-virtnet-io-v1alpha1-subnet
        port: 8081
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGekNDQWYrZ0F3SUJBZ0lRZUZJMnpEZTRRMGdEV1hGaEp0a0hkakFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwMmFYSjBibVYwTG1sdk1DQVhEVEkwTURJd05UQTNOVEV4TUZvWUR6SXlNak14TWpFNQpNRGMxTVRFd1dqQVZNUk13RVFZRFZRUURFd3AyYVhKMGJtVjBMbWx2TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBeTF5SWRJK0lKR2FnYUR3MFRmNlVVUmNJSVN4UkJyeWREaC94SkdpR3NhdHcKaVdacjBVVi8wdkx6VWpkUlk5Tm5YS3VENGFycWl4MlA2TWQrbzBWYkJkV25CZ0RzSEx4TlpETlhWQ0E2cUZoQgpFRGY5MzBrbWg5UG9CTTFPS0pvZkxsL095cDVWWWY1U0Z4Y3FpUVIxSENXZSs4VC9tZ1U0bVhaYlQ1VTFNb1dTCnVYR3FERFY0M3NPMWNweXh4REZJU0ZGbVp0eVNLelRFM1dvRWw2UWhHWXFSaXhzT0JXWlF2andlL0V0QmFTSFAKOHlxaUd2Nmk5aDZnSzRtUVA0TkltRkpmTlc3aU83V2MyT09lMmhTZXd5YXYvNWlXWUhwT1RWbEozMWk1bVpXMwpvMjZ0TmNsZHU4cXRCUllJUG1zSHFnZnREYm84d3pJejc1bGFUU2Z4ZFFJREFRQUJvMkV3WHpBT0JnTlZIUThCCkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIKL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkJwc3E2TFNoaHpIWm1ydmtNUVd5RmxON1Vha01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNERTd1VUJQYkFlaVJlc0V0VFIyNXVKa3FHdW4vSTJkN28rT0VVa0tuYTh0Uk9VQnEyCkFhWVVxWlNNQVJBNm9YaHBaVUFvb3Y2VmRaOEIxS3hUak5YdzU4T01LK2kwWmxoS2lqVTNsOWIrTkVtQ1I1NFEKeVJ0NXljVFJZb1ljYzNBUDJEcGNSMXBxcXdoUG1lM0lnOUszYVgvVWFneFFWZmFQanBBSUFkd2hCSHZVY2VUdwpXaVowNG9tM0pBNmtLQXIrZVBjRU5kcWJLSVRrZVZVTE9jVVNhc3YwSnAyZXNsNjhRb2d0dEVRcEhhRHdVR2tWCjByc2R2ZDM4MzZoZ2tRbE53Y2l1cW9EN0Y2VFVORitPdEdObDExNDY1d1dueEI0eTI4YWZpOGYxT3U4YWJDdUgKSFVtLzJuZ3VWdEk2UEhLOXZoM0E4eFZCbng4S1Q4b0psNzgrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      # caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUYrakNDQStLZ0F3SUJBZ0lKQU0vbDdWd1F1L3VPTUEwR0NTcUdTSWIzRFFFQkRRVUFNRjB4Q3pBSkJnTlYKQkFZVEFrTk9NUkV3RHdZRFZRUUlEQWhUYUdGdVowaGhhVEVSTUE4R0ExVUVCd3dJVTJoaGJtZElZV2t4RVRBUApCZ05WQkFvTUNFUmhiME5zYjNWa01SVXdFd1lEVlFRRERBd3hPVEl1TVRZNExqRXVNVFl3SUJjTk1qUXdNVEl3Ck1EUXdPVEE1V2hnUE1qRXlNekV5TWpjd05EQTVNRGxhTUYweEN6QUpCZ05WQkFZVEFrTk9NUkV3RHdZRFZRUUkKREFoVGFHRnVaMGhoYVRFUk1BOEdBMVVFQnd3SVUyaGhibWRJWVdreEVUQVBCZ05WQkFvTUNFUmhiME5zYjNWawpNUlV3RXdZRFZRUUREQXd4T1RJdU1UWTRMakV1TVRZd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3CmdnSUtBb0lDQVFDNEhjS1FkcHFZSENuVXFnK2JRS08rWTRSaUJ1NmduS21Zcmo3emc4Vm5mbmpIamY3UElPODIKMlJrTE1VbTdvWE1Fd0NNVFVVcjBmOEZTWTU2MHBZSTVEQmpzbXhsaGVnWFhZT1VDODFUVXFQaGV6TElUVmd5Rwo5RzY1NWVIZWNGY1V3ajNpOU84dUZoNTZBYnNkZjMzbXN0aGFjdGZDVytvMjRDUmdabVBpMGtuMEVsZmJRMXRDCmFXS2pFYjY2Y0dpSjVQS0lLOTFDQTl6NzFFTGg4NDlkV0RBZ2tSY2FVMi9aTngydTkwSkhXanRZS2RsQlZBaC8KM1FNSEFYTmM3am9WYzd1dXlrVkF0SGtxZExKWHVLTE9BSXc3UjVXeVFsdXhVYldLOGlLK1IwMnZoSnl6aThiSAo1b2dIVDVZT21PNXlKcW94S3JHaHZKYXpCVktSUzIxbHVDaUJzeWtHeitVZ09tb0hoblpGV0NlOVBqOWpranh0ClEvNGJBWVBObWxZazJwbCs4S1FjT0ZNaFhOOVU5dVdMQVltaGVXa2VTTTNDSmZ5NHNRMFJLUGd1Lys5UERtN1YKc1BNYkx0OVNsdlc2WFQrc0tYUnhDMXltUWp1SHhDWjRxemVHUEJsMGpOTmtqQkVKb0orS2JBYnVaZ2doTHdQbwpDbkUvOGVtQ0huOCs1N1hkcDg4TTJHWFRoNCs0dkJlVEE3M2c4cllSeFNYQTM0UGxwT1hndmw0T3RJRXhXOG9BCjhPK1BheUF2dGdzc3IrOFhiS3pYQ2hpVzVERGpROER3L1oxSkhzbDFkRjc5WjFIWlBTVitLNWdwVXJMMlB4RjgKWGcyNVpEZXc4bHo3TnhpYyticXloWExLQmRXc2lKZjkzYlZtcTNQcTllZ09qTGRTeWlPN0dRSURBUUFCbzRHNgpNSUczTUhjR0ExVWRJd1J3TUc2aFlhUmZNRjB4Q3pBSkJnTlZCQVlUQWtOT01SRXdEd1lEVlFRSURBaFRhR0Z1ClowaGhhVEVSTUE4R0ExVUVCd3dJVTJoaGJtZElZV2t4RVRBUEJnTlZCQW9NQ0VSaGIwTnNiM1ZrTVJVd0V3WUQKVlFRRERBd3hPVEl1TVRZNExqRXVNVGFDQ1FEakxwRzJyMlRmdURBSkJnTlZIUk1FQWpBQU1Bc0dBMVVkRHdRRQpBd0lFOERBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQVBCZ05WSFJFRUNEQUdod1RBcUFFUU1BMEdDU3FHClNJYjNEUUVCRFFVQUE0SUNBUUNmbFNDTWFCb3FKZFV0aEtldS8zb3NaMGp2MVFUU3hRSk9BdGZYRW1aWmFwNUcKYlM0blhYU0EwSVBmOEdjeFZncWdxc0xadjllaFpCZWZ1RndLK3Yzc0RiaGV0S0s1MTZKbkoxUmZvZW9xa2JCbgpCSTBnOFJPYVY5b2xIa2xuUytrOERZTGlkWVFDQnNCWG4zczh3Zy9zOWpPTHZsVVF6R3d6VWlMNy9rTjRDdzB1Cmpjd1dETTZPbkNiNkFoVjAvbklBbjVibTBKRm9NczBBNWFjQStreVp3ODV3TFRqa3dxWngzbmhQd3VpVW51UVAKZC8xSmg4c1JTK0dUbVc0cEw2VzBkZEdvbDdHc3o3QzUzb2dkNXVKYVJYTnJQck0zRE8vMHprYXpYd0JNczBVQgpndDhCZ2NZME90Yy9zT2VhSmk2UWcyYkIzZmsrUHRhc0kzVmxEY0VibzI3bWtjSjZCRUpONjV6T0Y4QUp6VEhHCnZPZUZMQTh5ajhpREg2ZVZkZHJkZmhxUTNjaFhybnBxbjNPQzVKR3BJZUtIM3JuakRNbUJ4MkZWY0xYNGZsckYKU1FuOXRXcnFONDQyVUdrUG9GYVVFVzZGR1Jsd2s0TlljYW1SYzZDNkdHZE1HRkJIWFk0ajBML1g5REpTam04dwo3U09QTE1BNUpEMjJWZmliVUpmYXEvVVNJaFNOUUY2M1BWQzJMODIzMWpPcDdLYWkwL3A1QXNtME5WKzlmendsCk1ETlVhOUNicUtjbFRhTldia0hwZW1nZTRIWVRnVUdqemVyd2dsamxZUi94dDVHRENVbkcxQWJtMGRUNisxblMKbFJVWkVlaTBNaCsyRTRaVHlQd2s0TU5hU2xoWlRBNVo3UEUxZVp6RDJ2VjExSy9vTTF3TWlVd3FDS3VLSkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    sideEffects: None
