kind: ConfigMap
apiVersion: v1
metadata:
  name: virtnest-multus
  namespace: {{ .Release.Namespace }}
data:
  cni-conf.json: |
    {
      "cniVersion": "0.3.1",
      "name": "multus-cni-network",
      "type": "multus",
      "confDir": "/etc/cni/net.d/",
      "logLevel": "debug",
      "logFile": "/var/log/multus.log",
      "capabilities": {
        "portMappings": true,
        "bandwidth": true
      },
      "namespaceIsolation": false,
      "clusterNetwork": "kindnet",
      "defaultNetworks": [],
      "multusNamespace": "{{ .Release.Namespace }}",
      "systemNamespaces": [],
      "kubeconfig": "/etc/kubernetes/admin.conf"
    }


# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: virtnest-multus
#   namespace: {{ .Release.Namespace }}
# data:
#   cni-conf.json: |
#     {
#       "cniVersion": "0.3.1",
#       "name": "multus-cni-network",
#       "type": "multus",
#       "confDir": "/etc/cni/net.d/",
#       "logLevel": "debug",
#       "logFile": "/var/log/multus.log",
#       "capabilities": {
#         "portMappings": true,
#         "bandwidth": true
#       },
#       "namespaceIsolation": false,
#       "clusterNetwork": "",
#       "defaultNetworks": [],
#       "multusNamespace": "{{ .Release.Namespace }}",
#       "systemNamespaces": [],
#       "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
#     }
