apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtnest
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - "*"
  - nonResourceURLs:
      - '*'
    verbs:
      - "*"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtnest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtnest
subjects:
  - kind: ServiceAccount
    name: virtnest-agent
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: virtnest-ctrl
    namespace: {{ .Release.Namespace }}
