/*
Copyright The Feather Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/hexiaodai/virtnet/pkg/k8s/apis/virtnet/v1alpha1"
	scheme "github.com/hexiaodai/virtnet/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BarrelsGetter has a method to return a BarrelInterface.
// A group's client should implement this interface.
type BarrelsGetter interface {
	Barrels() BarrelInterface
}

// BarrelInterface has methods to work with Barrel resources.
type BarrelInterface interface {
	Create(ctx context.Context, barrel *v1alpha1.Barrel, opts v1.CreateOptions) (*v1alpha1.Barrel, error)
	Update(ctx context.Context, barrel *v1alpha1.Barrel, opts v1.UpdateOptions) (*v1alpha1.Barrel, error)
	UpdateStatus(ctx context.Context, barrel *v1alpha1.Barrel, opts v1.UpdateOptions) (*v1alpha1.Barrel, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Barrel, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BarrelList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Barrel, err error)
	BarrelExpansion
}

// barrels implements BarrelInterface
type barrels struct {
	client rest.Interface
}

// newBarrels returns a Barrels
func newBarrels(c *VirtnestV1alpha1Client) *barrels {
	return &barrels{
		client: c.RESTClient(),
	}
}

// Get takes name of the barrel, and returns the corresponding barrel object, and an error if there is any.
func (c *barrels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Barrel, err error) {
	result = &v1alpha1.Barrel{}
	err = c.client.Get().
		Resource("barrels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Barrels that match those selectors.
func (c *barrels) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BarrelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BarrelList{}
	err = c.client.Get().
		Resource("barrels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested barrels.
func (c *barrels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("barrels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a barrel and creates it.  Returns the server's representation of the barrel, and an error, if there is any.
func (c *barrels) Create(ctx context.Context, barrel *v1alpha1.Barrel, opts v1.CreateOptions) (result *v1alpha1.Barrel, err error) {
	result = &v1alpha1.Barrel{}
	err = c.client.Post().
		Resource("barrels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(barrel).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a barrel and updates it. Returns the server's representation of the barrel, and an error, if there is any.
func (c *barrels) Update(ctx context.Context, barrel *v1alpha1.Barrel, opts v1.UpdateOptions) (result *v1alpha1.Barrel, err error) {
	result = &v1alpha1.Barrel{}
	err = c.client.Put().
		Resource("barrels").
		Name(barrel.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(barrel).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *barrels) UpdateStatus(ctx context.Context, barrel *v1alpha1.Barrel, opts v1.UpdateOptions) (result *v1alpha1.Barrel, err error) {
	result = &v1alpha1.Barrel{}
	err = c.client.Put().
		Resource("barrels").
		Name(barrel.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(barrel).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the barrel and deletes it. Returns an error if one occurs.
func (c *barrels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("barrels").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *barrels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("barrels").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched barrel.
func (c *barrels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Barrel, err error) {
	result = &v1alpha1.Barrel{}
	err = c.client.Patch(pt).
		Resource("barrels").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
