apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  labels:
    app: samplepod
spec:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: unlikely-to-exist-label
  #               operator: Exists
  containers:
    - name: samplepod
      command: ["sleep", "99999"]
      image: alpine
