// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1alpha1/coordinator/coordinator.proto

package coordinator

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetCoordinatorConfigRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCoordinatorConfigRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCoordinatorConfigRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCoordinatorConfigRequestMultiError, or nil if none found.
func (m *GetCoordinatorConfigRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCoordinatorConfigRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetPodName()) < 1 {
		err := GetCoordinatorConfigRequestValidationError{
			field:  "PodName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPodNamespace()) < 1 {
		err := GetCoordinatorConfigRequestValidationError{
			field:  "PodNamespace",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetCoordinatorConfigRequestMultiError(errors)
	}

	return nil
}

// GetCoordinatorConfigRequestMultiError is an error wrapping multiple
// validation errors returned by GetCoordinatorConfigRequest.ValidateAll() if
// the designated constraints aren't met.
type GetCoordinatorConfigRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCoordinatorConfigRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCoordinatorConfigRequestMultiError) AllErrors() []error { return m }

// GetCoordinatorConfigRequestValidationError is the validation error returned
// by GetCoordinatorConfigRequest.Validate if the designated constraints
// aren't met.
type GetCoordinatorConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCoordinatorConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCoordinatorConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCoordinatorConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCoordinatorConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCoordinatorConfigRequestValidationError) ErrorName() string {
	return "GetCoordinatorConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCoordinatorConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCoordinatorConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCoordinatorConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCoordinatorConfigRequestValidationError{}

// Validate checks the field values on GetCoordinatorConfigReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCoordinatorConfigReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCoordinatorConfigReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCoordinatorConfigReplyMultiError, or nil if none found.
func (m *GetCoordinatorConfigReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCoordinatorConfigReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetCoordinatorConfigReplyMultiError(errors)
	}

	return nil
}

// GetCoordinatorConfigReplyMultiError is an error wrapping multiple validation
// errors returned by GetCoordinatorConfigReply.ValidateAll() if the
// designated constraints aren't met.
type GetCoordinatorConfigReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCoordinatorConfigReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCoordinatorConfigReplyMultiError) AllErrors() []error { return m }

// GetCoordinatorConfigReplyValidationError is the validation error returned by
// GetCoordinatorConfigReply.Validate if the designated constraints aren't met.
type GetCoordinatorConfigReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCoordinatorConfigReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCoordinatorConfigReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCoordinatorConfigReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCoordinatorConfigReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCoordinatorConfigReplyValidationError) ErrorName() string {
	return "GetCoordinatorConfigReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetCoordinatorConfigReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCoordinatorConfigReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCoordinatorConfigReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCoordinatorConfigReplyValidationError{}
